// Part of the microcontroller firmware code for Boldport's 'Scarab'
// Copyright (C) 2019  Saar Drimer
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see https://www.gnu.org/licenses/.


#include "mainControl.h"
#include "eventControl.h"
#include "timer.h"
#include "displayControl.h"
#include "touchControl.h"
#include "pwmControl.h"

#include "stdint.h"
#include "stdbool.h"

#include <atmel_start.h>


void setup()
{
	// Init MCU (generated by Atmel START)
	atmel_start_init();
    
    initEvents();   
    initTouch();
    initDisplay();
    initPwm();
    initMainControl();
}

int main(void)
{
    setup();
    eventLoop(); // never returns
}
